### ISSUE TITLE
[Features Request]Added Griefdefender&Griefprevention Support

### ISSUE THREAD

**Issue by ahdg6** [erikzimmermann/TradeSystem#305]
It would be awesome to trade GD claim blocks.

https://github.com/bloodmc/griefdefender

GD API:https://github.com/bloodmc/griefdefenderAPI (Jitpack)

**Comment by CodingAir** [comment]
bloodmc was contacted. Waiting for a response to get back to this.

**Comment by ahdg6** [comment]
https://github.com/CodingAir/TradeSystem/issues/324

**Comment by RareMaker50** [comment]
@ahdg6 I had contacted bloodmc about this not too long ago, and GriefDefender has an economy mode which is an easy alternative to being able to trade GD claim blocks since you just need to trade money since GD claim blocks just get taken out of your balance. It's a good temporary alternative since I don't know if this is possible now since he told me to do that, but if it gets added that's amazing, in the meanwhile that's what I'm using
